export const products = [
  {
    id: 1,
    title: "Black Automatic Watch",
    image: "/assets/product.jpg",
    category: "Accessories",
    review: 4.9,
    sales: 98,
    newPrice: 169.99,
    oldPrice: 199.99,
  },
  {
    id: 2,
    title: "Black Automatic Watch",
    image: "/assets/product.jpg",
    category: "Accessories",
    review: 4.9,
    sales: 98,
    newPrice: 169.99,
    oldPrice: 199.99,
  },
  {
    id: 3,
    title: "Black Automatic Watch",
    image: "/assets/product.jpg",
    category: "Accessories",
    review: 4.9,
    sales: 98,
    newPrice: 169.99,
    oldPrice: 199.99,
  },
  {
    id: 4,
    title: "Black Automatic Watch",
    image: "/assets/product.jpg",
    category: "Accessories",
    review: 4.9,
    sales: 98,
    newPrice: 169.99,
    oldPrice: 199.99,
  },
];
